export const members = [
 {
   "LName": "Jones",
   "DistrictNum": "1",
   "DISTRICT": "District 1",
   "Source": "http://www.sanjoseca.gov/index.aspx?NID=146",
   "CName": "Charles Jones",
   "Term_YRS": 4,
   "Term_Start": "11/1/18",
   "Term_End": "12/31/22",
   "TERM_REMAINING": 1243,
   "COMMITTEES": "Rules and Open Government Committee, Member; Public Safety, Finance, and Strategic Support Committee (PSFSS), Vice Chair; Smart Cities and Service Improvements Committee, Chair; Board of Fair Campaign & Political Practices (formerly Ethics Commission), Liaison; Work2future Board, Council Liaison; Santa Clara Valley Transportation Authority (VTA) Board of Directors, Member; Capital Projects Oversight Committee (CPOC); Safety, Security, and Transit Planning and Operations (SSTPO) Committee; Santa Clara VTA Policy Advisory Board – El Camino Real Rapid Transit, Alternate; Santa Clara County Cities Association Board, Member; City Selection Committee, Member; Legislative Action Committee, Member; Silicon Valley Regional Interoperability Project, Member; San Jose/Santa Clara Clean Water Financing Authority, Member; West Valley Sanitation District – Sewer Advisory Board, Member; Santa Clara Valley Habitat Agency Implementation Board, VTA Representative Alternate",
   "INCUMBENT": "Y",
   "WEB": "www.sjdistrict1.com",
   "EMAIL": "District1@sanjoseca.gov",
   "PHONE": "408.535.4901",
   "City_News": "https://www.sjdistrict1.com/district-1-newsletter/",
   "Blog": "https://www.sjdistrict1.com/news-and-press/",
   "TWITTER": "@chappiejones",
   "Facebook": "",
   "Liaison": "David Gomez",
   "Liaison PHONE": "",
   "LIASON EMAIL": "david.gomez@sanjoseca.gov",
   "Nextdoor": "https://nextdoor.com/agency-detail/ca/san-jose/san-jose-city-council/?i=gxssvwxjhatybvdjprrk",
   "Instagram": "",
   "CONFLICTS": 35,
   "DONORS": 156,
   "PERSONAL EMAIL": "chappiejones@yahoo.com",
   "Vote_Y": "91%",
   "Vote_N": "6%",
   "Vote_A": "3%",
   "Photo": "//d3ju1gh2kf3yfd.cloudfront.net/entite/D1_Chappie-Jones.jpg"
 },
 {
   "LName": "Jimenez",
   "DistrictNum": "2",
   "DISTRICT": "District 2",
   "Source": "http://www.sanjoseca.gov/index.aspx?NID=146",
   "CName": "Sergio Jimenez",
   "Term_YRS": 4,
   "Term_Start": "11/1/16",
   "Term_End": "12/31/20",
   "TERM_REMAINING": 513,
   "COMMITTEES": "City’s Transportation and Environment Committee, Public Safety Committee and Neighborhood Services Committee, Local Agency Formation Commission (LAFCO) and Association of Bay Area Governments (ABAG)",
   "INCUMBENT": "N",
   "WEB": "www.sanjoseca.gov/district2",
   "EMAIL": "District2@sanjoseca.gov",
   "PHONE": "408.535.4902",
   "City_News": "http://www.sanjoseca.gov/index.aspx?NID=5389",
   "Blog": "http://www.sanjoseca.gov/index.aspx?NID=5610",
   "TWITTER": "@D2SergioJimenez ",
   "Facebook": "",
   "Liaison": "Vanessa Sandoval",
   "Liaison PHONE": "408.535.4925",
   "LIASON EMAIL": "Vanessa.Sandoval@sanjoseca.gov",
   "Nextdoor": "https://nextdoor.com/agency-detail/ca/san-jose/san-jose-city-council/?i=gxssvwxjhatybvdjprrk",
   "Instagram": "",
   "CONFLICTS": 6,
   "DONORS": null,
   "PERSONAL EMAIL": "pattyejimenez@yahoo.com",
   "Vote_Y": "78%",
   "Vote_N": "14%",
   "Vote_A": "8%",
   "Photo": "//d3ju1gh2kf3yfd.cloudfront.net/entite/D2-Sergio-Jimenez.jpg"
 },
 {
   "LName": "Peralez",
   "DistrictNum": "3",
   "DISTRICT": "District 3",
   "Source": "http://www.sanjoseca.gov/index.aspx?NID=146",
   "CName": "Raul Peralez",
   "Term_YRS": 4,
   "Term_Start": "11/1/18",
   "Term_End": "12/31/22",
   "TERM_REMAINING": 1243,
   "COMMITTEES": "Public Safety; Finance; & Strategic Services Committee (Chair); Transportation & Environment Committee; Community & Economic Development Committee; Ad-Hoc Committee for Construction & Development Services; Association of Bay Area Governments (ABAG) Executive Board; ABAG Administrative Committee; Airport Commission (Liaison); Capitol Corridor Joint Powers Authority; Downtown Parking Board (Liaison); Hammer Theater Advisory Committee; League of California Cities – Latino Caucus; Mayor’s Gang Prevention Task Force; Team San Jose Board (Liaison); Santa Clara County Reentry Network; Santa Clara Valley Transportation Authority Board (VTA); VTA Policy Advisory Board – Diridon Station (Chair); VTA Congestion Management Program and Planning (Chair); VTA Governance & Audit Committee",
   "INCUMBENT": "Y",
   "WEB": "sjd3.com",
   "EMAIL": "District3@sanjoseca.gov",
   "PHONE": "408.535.4903",
   "City_News": "https://sjd3.com/by-date/",
   "Blog": "",
   "TWITTER": "@D3SanJose",
   "Facebook": "",
   "Liaison": "Christina Ramos",
   "Liaison PHONE": "408.535.4934",
   "LIASON EMAIL": "christina.m.ramos@sanjoseca.gov",
   "Nextdoor": "https://nextdoor.com/agency-detail/ca/san-jose/san-jose-city-council/?i=gxssvwxjhatybvdjprrk",
   "Instagram": "",
   "CONFLICTS": 11,
   "DONORS": 350,
   "PERSONAL EMAIL": "raul@raulperalez.com",
   "Vote_Y": "95%",
   "Vote_N": "4%",
   "Vote_A": "1%",
   "Photo": "//d3ju1gh2kf3yfd.cloudfront.net/entite/D3-Raul-Peralez.jpg"
 },
 {
   "LName": "Diep",
   "DistrictNum": "4",
   "DISTRICT": "District 4",
   "Source": "http://www.sanjoseca.gov/index.aspx?NID=146",
   "CName": "Lan Diep",
   "Term_YRS": 4,
   "Term_Start": "11/1/16",
   "Term_End": "12/31/20",
   "TERM_REMAINING": 513,
   "COMMITTEES": "",
   "INCUMBENT": "N",
   "WEB": "www.sanjoseca.gov/index.aspx?NID=152",
   "EMAIL": "District4@sanjoseca.gov",
   "PHONE": "408.535.4904",
   "City_News": "http://www.sanjoseca.gov/index.aspx?nid=3304",
   "Blog": "",
   "TWITTER": "@SanJoseD4 ",
   "Facebook": "",
   "Liaison": "Chris Rork",
   "Liaison PHONE": "",
   "LIASON EMAIL": "Christopher.Rork@sanjoseca.gov",
   "Nextdoor": "https://nextdoor.com/agency-detail/ca/san-jose/san-jose-city-council/?i=gxssvwxjhatybvdjprrk",
   "Instagram": "",
   "CONFLICTS": 15,
   "DONORS": 21,
   "PERSONAL EMAIL": "lan@lanforsanjose.com",
   "Vote_Y": "83%",
   "Vote_N": "10%",
   "Vote_A": "7%",
   "Photo": "//d3ju1gh2kf3yfd.cloudfront.net/entite/D4-Lan-Diep.jpg"
 },
 {
   "LName": "Carrasco",
   "DistrictNum": "5",
   "DISTRICT": "District 5",
   "Source": "http://www.sanjoseca.gov/index.aspx?NID=146",
   "CName": "Magdalena Carrasco",
   "Term_YRS": 4,
   "Term_Start": "11/1/18",
   "Term_End": "12/31/22",
   "TERM_REMAINING": 1243,
   "COMMITTEES": "Ad-Hoc Housing Construction and Development Committee, Chair; Neighborhood Services and Education, Vice Chair; Public Safety, Finance & Strategic Support, Member; Valley Transportation Authority, Board Member; Sister Cities International Board of Directors, Member; Valley Transportation Authority, CMPP, Member; Valley Transportation Authority, Downtown/ East Valley Policy Advisory Committee, Member; Human Services Commission, Liaison",
   "INCUMBENT": "Y",
   "WEB": "www.sanjoseca.gov/index.aspx?NID=150",
   "EMAIL": "District5@sanjoseca.gov",
   "PHONE": "408.535.4905",
   "City_News": "http://www.sanjoseca.gov/index.aspx?NID=4660",
   "Blog": "",
   "TWITTER": "@CM_Magdalena",
   "Facebook": "https://www.facebook.com/VM.MagdalenaCarrasco",
   "Liaison": "Frances Herbert",
   "Liaison PHONE": "408.535.4948",
   "LIASON EMAIL": "frances.herbert@sanjoseca.gov",
   "Nextdoor": "https://nextdoor.com/agency-detail/ca/san-jose/san-jose-city-council/?i=gxssvwxjhatybvdjprrk",
   "Instagram": "https://www.instagram.com/cm_magdalena/",
   "CONFLICTS": 5,
   "DONORS": 467,
   "PERSONAL EMAIL": "voteformagdelena@gmail.com",
   "Vote_Y": "92%",
   "Vote_N": "6%",
   "Vote_A": "2%",
   "Photo": "//d3ju1gh2kf3yfd.cloudfront.net/entite/D5-Magdalena-Carassco.jpg"
 },
 {
   "LName": "Davis",
   "DistrictNum": "6",
   "DISTRICT": "District 6",
   "Source": "http://www.sanjoseca.gov/index.aspx?NID=146",
   "CName": "Devora “Dev” Davis",
   "Term_YRS": 4,
   "Term_Start": "11/1/16",
   "Term_End": "12/31/20",
   "TERM_REMAINING": 513,
   "COMMITTEES": "Chair of the Transportation & Environment Committee; Member of the Rules Committee; Member of AD-HOC Committee for Housing Construction & Development Services; Member of the Smart Cities & Innovation Committee; Member of the San Jose/Santa Clara Treatment Plant Advisory Committee (TPAC); Council Liaison to the Federated Retirement Board Council Liaison to the Historic Landmarks Commission; Council Liaison to the Santa Clara County Emergency Operational Area Council (formerly Emergency Preparedness Council); Caltrain San Jose Representative on Joint Powers Board (JPB); Caltrain San Jose Representative on Local Policy Maker Group (LPMG); Caltrain Member of the Ad-Hoc Committee on Positive Train Control/Communications - Based Overlay Signal System (PTC/CBOSS); Caltrain Member of the Centralized Equipment Maintenance & Operations Facilities Oversight Committee (CEMOF); VTA Alternate Member for the Board; VTA Member of the Diridon Station Joint Policy Advisory Board; VTA Member of the El Camino Real Grand Boulevard Initiative; VTA Alternate Member for Safety, Security, and Transit Planning and Operations (SSTPO); San Jose Sports Authority Board of Directors – City Council Liaison; San Jose Arena Authority Board of Directors – City Council Liaison; Grand Boulevard Initiative Task Force – City Council Liaison; SJ/SC Treatment Plant Advisory Committee - City Council Liaison",
   "INCUMBENT": "N",
   "WEB": "www.sjd6.org/",
   "EMAIL": "district6@sanjoseca.gov",
   "PHONE": "408.535.4906",
   "City_News": "https://sjd6.org/newsletter/",
   "Blog": "",
   "TWITTER": "@DevDavisCA",
   "Facebook": "https://www.facebook.com/devdavisCA/",
   "Liaison": "Mary Anne Groen",
   "Liaison PHONE": "",
   "LIASON EMAIL": "maryanne.groen@sanjoseca.gov",
   "Nextdoor": "https://nextdoor.com/agency-detail/ca/san-jose/san-jose-city-council/?i=gxssvwxjhatybvdjprrk",
   "Instagram": "https://www.instagram.com/devdavisca/",
   "CONFLICTS": 5,
   "DONORS": null,
   "PERSONAL EMAIL": "",
   "Vote_Y": "89%",
   "Vote_N": "5%",
   "Vote_A": "6%",
   "Photo": "//d3ju1gh2kf3yfd.cloudfront.net/entite/D6-Dev-Davis.jpg"
 },
 {
   "LName": "Esparza",
   "DistrictNum": "7",
   "DISTRICT": "District 7",
   "Source": "http://www.sanjoseca.gov/index.aspx?NID=146",
   "CName": "Maya Esparza",
   "Term_YRS": 4,
   "Term_Start": "11/1/18",
   "Term_End": "12/31/22",
   "TERM_REMAINING": 1243,
   "COMMITTEES": "",
   "INCUMBENT": "N",
   "WEB": "www.sanjoseca.gov/index.aspx?NID=154",
   "EMAIL": "District7@sanjoseca.gov",
   "PHONE": "408.535.4907",
   "City_News": "",
   "Blog": "",
   "TWITTER": "@MayaEsparza3 ",
   "Facebook": "",
   "Liaison": "Andrés Quintero",
   "Liaison PHONE": "",
   "LIASON EMAIL": " Andres.Quintero@sanjoseca.gov",
   "Nextdoor": "https://nextdoor.com/agency-detail/ca/san-jose/san-jose-city-council/?i=gxssvwxjhatybvdjprrk",
   "Instagram": "",
   "CONFLICTS": 2,
   "DONORS": 659,
   "PERSONAL EMAIL": "info@mayaesparza.com",
   "Vote_Y": "92%",
   "Vote_N": "2%",
   "Vote_A": "6%",
   "Photo": "//d3ju1gh2kf3yfd.cloudfront.net/entite/D7-Esparza-Maya.png"
 },
 {
   "LName": "Arenas",
   "DistrictNum": "8",
   "DISTRICT": "District 8",
   "Source": "http://www.sanjoseca.gov/index.aspx?NID=146",
   "CName": "Sylvia Arenas",
   "Term_YRS": 4,
   "Term_Start": "11/1/16",
   "Term_End": "12/31/20",
   "TERM_REMAINING": 513,
   "COMMITTEES": "Neighborhood Services & Education Committee – Vice Chair; Transportation & Environment Committee – Member; Ad-Hoc Committee for Development Services – Member; Habitat Conservation Agency Governing Board – Board Member; Habitat Conservation Agency Implementation Board – Member; VTA Downtown/East Valley Policy Advisory Board – Member; Appeals Hearing Board – Liaison; Schools City Collaborative – Member; SJ/SC Treatment Plant Advisory (TPAC) Committee – Alternate; Recycled Water Policy Advisory Committee – Member; Santa Clara County Local Agency Formation (LAFCO)  – Alternate",
   "INCUMBENT": "N",
   "WEB": "www.sanjoseca.gov/index.aspx?NID=156",
   "EMAIL": "district8@sanjoseca.gov",
   "PHONE": "408.535.4908",
   "City_News": "",
   "Blog": "",
   "TWITTER": "@SylviaArenas ",
   "Facebook": "https://www.facebook.com/councilwomansylviaarenas",
   "Liaison": "Patrick McGarrity",
   "Liaison PHONE": "408-535.4969",
   "LIASON EMAIL": "patrick.mcgarrity@sanjoseca.gov",
   "Nextdoor": "https://nextdoor.com/agency-detail/ca/san-jose/san-jose-city-council/?i=gxssvwxjhatybvdjprrk",
   "Instagram": "",
   "CONFLICTS": 0,
   "DONORS": 17,
   "PERSONAL EMAIL": "arenasldf@deaneandcompany.com",
   "Vote_Y": "82%",
   "Vote_N": "3%",
   "Vote_A": "15%",
   "Photo": "//d3ju1gh2kf3yfd.cloudfront.net/entite/D8-Sylvia-Arenas.jpg"
 },
 {
   "LName": "Foley",
   "DistrictNum": "9",
   "DISTRICT": "District 9",
   "Source": "http://www.sanjoseca.gov/index.aspx?NID=146",
   "CName": "Pam Foley",
   "Term_YRS": 4,
   "Term_Start": "11/1/18",
   "Term_End": "12/31/22",
   "TERM_REMAINING": 1243,
   "COMMITTEES": "San José Learns Task Force; Ad-Hoc Committee for Development Services (Member); Community & Economic Development Committee (Member); Neighborhood Services & Education Committee (Member); Association of Bay Area Governments -ABAG (Alternate); Appeals Hearing Board (Liaison); Citizen Corps Council (Vice Chair); Emergency Preparedness Council; Police & Fire Retirement Board (Non-Voting Member); Recycling & Waste Reduction Commission of Santa Clara County; Santa Clara Valley Habitat Agency Governing Board; Santa Clara Valley Habitat Agency Implementation Board (Alternate); Santa Clara Valley Water District - Water Commission (2-year Appointment); Silicon Valley Interoperability Project",
   "INCUMBENT": "N",
   "WEB": "www.sanjoseca.gov/index.aspx?NID=155",
   "EMAIL": "District9@sanjoseca.gov",
   "PHONE": "408.535.4909",
   "City_News": "",
   "Blog": "",
   "TWITTER": "@PamFoleyD9 ",
   "Facebook": "",
   "Liaison": "Scott Hughes",
   "Liaison PHONE": "",
   "LIASON EMAIL": "scott.hughes@sanjoseca.gov",
   "Nextdoor": "https://nextdoor.com/agency-detail/ca/san-jose/san-jose-city-council/?i=gxssvwxjhatybvdjprrk",
   "Instagram": "",
   "CONFLICTS": 6,
   "DONORS": 631,
   "PERSONAL EMAIL": "pam@foleymg.com",
   "Vote_Y": "89%",
   "Vote_N": "6%",
   "Vote_A": "5%",
   "Photo": "//d3ju1gh2kf3yfd.cloudfront.net/entite/D9-Foley_Pam.jpg"
 },
 {
   "LName": "Khamis",
   "DistrictNum": "10",
   "DISTRICT": "District 10",
   "Source": "http://www.sanjoseca.gov/index.aspx?NID=146",
   "CName": "Johnny Khamis",
   "Term_YRS": 4,
   "Term_Start": "11/1/16",
   "Term_End": "12/31/20",
   "TERM_REMAINING": 513,
   "COMMITTEES": "Rules Committee; Public Safety, Finance, & Strategic Support Committee; Community & Economic Development - Chairperson; Federated Employees Retirement Board - Non-Voting; Santa Clara County Local Agency Formation; Santa Clara Valley Transportation Authority Board; Santa Clara Valley Transportation Governance and Audit Committee; Santa Clara Valley Transportation Transit Planning and Operations Committee - Chairperson; Strategic Planning Advisory Board; Civil Service Commission; Deferred Compensation Advisory Committee; Parks & Recreation Commission; Senior Citizens Commission",
   "INCUMBENT": "Y",
   "WEB": "www.sjd10.com",
   "EMAIL": "District10@sanjoseca.gov",
   "PHONE": "408.535.4910",
   "City_News": "http://www.sjd10.com/d10-accomplishments.html",
   "Blog": "http://www.sjd10.com/newsletter-archives.html",
   "TWITTER": "@JohnnyKhamis",
   "Facebook": "",
   "Liaison": "Shane Patrick Connolly",
   "Liaison PHONE": "",
   "LIASON EMAIL": "shane.connolly@sanjoseca.gov",
   "Nextdoor": "https://nextdoor.com/agency-detail/ca/san-jose/san-jose-city-council/?i=gxssvwxjhatybvdjprrk",
   "Instagram": "",
   "CONFLICTS": 20,
   "DONORS": null,
   "PERSONAL EMAIL": "",
   "Vote_Y": "87%",
   "Vote_N": "3%",
   "Vote_A": "10%",
   "Photo": "//d3ju1gh2kf3yfd.cloudfront.net/entite/D10-Khamis-John.png"
 },
 {
   "LName": "Liccardo",
   "DistrictNum": "Mayor",
   "DISTRICT": "Mayor",
   "Source": "http://www.sanjoseca.gov/index.aspx?NID=146",
   "CName": "Sam Liccardo",
   "Term_YRS": 4,
   "Term_Start": "11/1/18",
   "Term_End": "12/31/22",
   "TERM_REMAINING": 1243,
   "COMMITTEES": "",
   "INCUMBENT": "Y",
   "WEB": "http://www.sanjoseca.gov/index.aspx?NID=203",
   "EMAIL": "mayoremail@sanjoseca.gov",
   "PHONE": "408.535.4800 ",
   "City_News": "http://www.sanjoseca.gov/index.aspx?nid=661",
   "Blog": "http://www.sanjoseca.gov/index.aspx?NID=5262",
   "TWITTER": "@sliccardo ",
   "Facebook": "https://www.facebook.com/SamLiccardo1/",
   "Liaison": "Jim Reed",
   "Liaison PHONE": "",
   "LIASON EMAIL": "jim.reed@sanjoseca.gov",
   "Nextdoor": "https://nextdoor.com/agency-detail/ca/san-jose/san-jose-city-council/?i=gxssvwxjhatybvdjprrk",
   "Instagram": "https://www.instagram.com/samliccardo/?ref=badge",
   "CONFLICTS": 89,
   "DONORS": 2348,
   "PERSONAL EMAIL": "",
   "Vote_Y": "96%",
   "Vote_N": "2%",
   "Vote_A": "2%",
   "Photo": "//d3ju1gh2kf3yfd.cloudfront.net/entite/Mayor-Sam-Liccardo.jpg"
 }
]